### ISSUE TITLE
java.io.IOException: Cannot run program "/opt/local/bin/dot": error=2, No such file or directory

### ISSUE THREAD

**Issue by Lyannic** [sitoolkit/sit-cv#85]
Hello,
I am trying to generate Class diagrams for my Java project. 
However when I try to execute the gradle task cvReport, I get the following exception:

> java.io.IOException: Cannot run program "/opt/local/bin/dot": error=2, No such file or directory
> 	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
> 	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
> 	at java.base/java.lang.Runtime.exec(Runtime.java:591)
> 	at net.sourceforge.plantuml.cucadiagram.dot.ProcessRunner$MainThread.startThreads(ProcessRunner.java:163)
> 	at net.sourceforge.plantuml.cucadiagram.dot.ProcessRunner$MainThread.runJob(ProcessRunner.java:123)
> 	at net.sourceforge.plantuml.api.TimeoutExecutor$MyThread.run(TimeoutExecutor.java:79)
> Caused by: java.io.IOException: error=2, No such file or directory
> 	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
> 	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:340)
> 	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:271)
> 	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
> 	... 5 more
> java.io.IOException: Cannot run program "/opt/local/bin/dot": error=2, No such file or directory
> 	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
> 	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
> 	at java.base/java.lang.Runtime.exec(Runtime.java:591)
> 	at net.sourceforge.plantuml.cucadiagram.dot.ProcessRunner$MainThread.startThreads(ProcessRunner.java:163)
> 	at net.sourceforge.plantuml.cucadiagram.dot.ProcessRunner$MainThread.runJob(ProcessRunner.java:123)
> 	at net.sourceforge.plantuml.api.TimeoutExecutor$MyThread.run(TimeoutExecutor.java:79)
> Caused by: java.io.IOException: error=2, No such file or directory
> 	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
> 	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:340)
> 	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:271)
> 	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
> 	... 5 more

I am using version 1.0.0-beta.2.

I found out that this has to do with graphviz. When I install graphviz on my machine, the task finishes without any problems. However, since you don't mention in the README that graphviz needs to be installed locally, I expect that graphviz is being supplied by your plugin itself.

Thank you in advance for any help.

**Comment by kfujinuma** [comment]
Thank you for your report.
As you have done, installing Graphviz is needed to use SIT-CV.
We Added the description to the [README](https://github.com/sitoolkit/sit-cv/blob/develop/README.md).

**Comment by Lyannic** [comment]
Thank you for the fast reply.
